name: Block Unauthorized Direct Pushes to main

on:
  push:
    branches:
      - main

jobs:
  check-author:
    runs-on: ubuntu-latest
    steps:
      - name: Get git author
        id: get-author
        run: |
          AUTHOR=$(git log -1 --pretty=%an)
          echo "Author: $AUTHOR"
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

      - name: Fail if not repo owner
        if: env.AUTHOR != 'MrKrypex0'
        run: |
          echo "❌ ERROR: Only the repo owner is allowed to push directly to main."
          exit 1
