name: Require External Review for Contributors

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-review-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        id: pr
        uses: tibdex/github-action-get-pr@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract author and reviewers
        id: extract
        run: |
          echo "PR Author: ${{ steps.pr.outputs.author }}"
          echo "Approved by: ${{ steps.pr.outputs.approved_by }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

          echo "::set-output name=author::${{ steps.pr.outputs.author }}"
          echo "::set-output name=approved_by::${{ steps.pr.outputs.approved_by }}"

      - name: Fail if contributor approves own PR
        if: |
          steps.extract.outputs.author != 'MrKrypex0' && 
          !contains(steps.extract.outputs.approved_by, 'MrKrypex0')
        run: |
          echo "❌ This PR was created by a contributor and has not been approved by MrKrypex0."
          echo "Please wait for manual review before merging."
          exit 1

      - name: Allow owner to self-approve
        if: |
          steps.extract.outputs.author == 'MrKrypex0' && 
          contains(steps.extract.outputs.approved_by, 'MrKrypex0')
        run: |
          echo "✅ This PR was created and approved by the owner. Merging is allowed."